
# 设备配置
device:
  use_cuda: true
  use_data_parallel: true
  gpu_device_ids: [0, 1]
  use_mixed_precision: true

# 通用训练参数
training:
  loss_function: "MSELoss"
  scheduler: "ReduceLROnPlateau"
  early_stopping_patience: 150

# 模型配置
model:
  name_0: "EnhancedCARNet_v2"
  name_1: "EnhancedCARNet_v2"
  hidden_size: 512
  num_heads: 8
  dropout: 0.2

# 训练参数_0 (单任务温度预测)
training_0:
  epochs: 400
  batch_size: 2048
  learning_rate: 0.00001
  weight_decay: 0.0001
  momentum: 0.9
  patience: 10
  optimizer: "AdamW"
  scheduler: "ReduceLROnPlateau"
  early_stopping_patience: 150
  loss_function: "MSELoss"

# 训练参数_1 (多任务预测)
training_1:
  epochs: 400
  batch_size: 256
  learning_rate: 0.0001
  weight_decay: 0.0001
  momentum: 0.9
  patience: 10
  optimizer: "AdamW"
  scheduler: "ReduceLROnPlateau"
  early_stopping_patience: 150
  loss_function: "MSELoss"

# 损失权重配置_1
loss_weights:
  T_weight: 0.00008331  # 1/12002
  atm_weight: 0.08332639  # 1000/12002
  u_weight: 0.08332639  # 1000/12002
  v_weight: 0.83326389  # 10000/12002
  divergence_weight: 0.2
  physics_weight: 0.5
  physics_equations:
    equation_1: 1
    equation_2: 1
    equation_3: 1
    equation_4: 1
    equation_5: 1
    equation_6: 1
    equation_7: 1

# 数据预处理配置
data:
  # 这些数据需要在运行时从数据预处理函数中获取
  # 不能直接存储在YAML中，因为它们是numpy数组
  preprocessing_functions:
    data_0: "data_preprocessing_0"
    data_1: "data_preprocessing_1"
