Data:
  data_path: "/home/yxfeng/project2/sci925/data/三维双热通量.xlsx"  # 输入数据路径（Excel）
  format: "auto"                 # auto|excel|csv （强制解析格式）
  sheet: 0   
  index_start: 8                  # Excel工作表索引或名称（仅excel）
  phase1_index_end: 15698         # 前382行为阶段1
  features: ["% x", "y", "z"]         # 特征列
  phase1_targets: ["T (K)"]        # 阶段1目标
  phase2_targets: ["T (K)", "u (m/s)", "v (m/s)", "p (Pa)"]  # 阶段2目标
  output_dir: "/home/yxfeng/project2/sci925/outputs"      # 结果输出目录（绝对路径）
  log_dir: "/home/yxfeng/project2/sci925/logs"      # 日志输出目录（绝对路径）
  test_ratio: 0.2               # 在各自阶段上的验证/测试占比
  random_state: 42
  scaler_name: "standardscaler"
  batch_size1: 64
  batch_size2: 64

Train:
  epochs: 1000
  optimizer: 'adam'
  loss_function: 'mse'
  scheduler: 'cosine'
  save_model_path: 'models'
  save_best_model_only_path: 'models/best'
  load_model_path: 'models'
  log_interval: 10
  log_dir: 'logs'
  log_freq: 10
  is_log: True
  device: 'cuda'
  save_freq: 100
  is_save: True
  early_stopping: True
  patience: 50
  min_delta: 1e-4
  save_best_only: True
  optimizer_config: {}
  loss_function_config: {}
  scheduler_config: {}
  metrics_dir: '/home/yxfeng/project2/sci925/outputs/metrics'


Optimizer:
  name: 'adam'
  name_list :
    - 'adam'
    - 'sgd'
    - 'adamw'
  lr_range: (1e-3,1e-4)
  weight_decay_range: (1e-5,1e-6)
  lr: 1e-3
  weight_decay: 1e-5
  betas: (0.9,0.999)
  momentum: 0.9
  eps: 1e-8

Scheduler:
  name: 'cosine'
  lr_min: 1e-6
  lr_max: 1e-3
  T_max: 100
  eta_min: 1e-6
  last_epoch: -1
  verbose: False

LossFunction:
  name: 'mse'

logger:
  name: 'logger'
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    - name: 'file_handler'
      level: 'INFO'
      formatter: 'simple'
      filename: 'logs/logger.log'


Model:
  model_name:
    phase1: 'mlp'
    phase2: 'mlp'
  phase_ls: [1,2]
  name_list: 
    - 'mlp'
    - 'lstm'
  input_dim: 3
  dropout: 0.2
  


 

  mlp:
    hidden_dim: [128, 64, 32]
    output_dim1: 1
    output_dim2: 4
    num_blocks: 5
  lstm:
    hidden_dim: [128, 64, 32]
    output_dim1: 1
    output_dim2: 4
    num_blocks: 5

